version: '3'

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
    - ./:/var/www:cached
    ports:
      - "9000:9000"

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
    - 8080:80
    volumes:
    - ./:/var/www:cached
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
    - php
    - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my_conf:/etc/mysql/conf.d/
    ports:
      - ${DB_PORT}:3306